server:
  port: 2245
spring:
  application:
    name: CLOUD-AUTH
  cloud:
    nacos:
      discovery:
        server-addr: http://nacos:8848/ #Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: http://sentinel:8080/ #配置Sentinel dashboard地址
        port: 8719

  datasource:
    url: jdbc:mysql://mysql:3306/wrc_cloud?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: wrc8848
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Shanghai
  redis:
    host: redis


mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml
#  typeAliasesPackage: com.wrc.cloud.entity


management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true # 激活Sentinel对Feign的支持




jwt:
  token:
    secret: 0s58aIHircc1emsIrZ6+KrNvzRxIaivxjWY/j4eQNxg=
    expireTime: 3600000
