server:
  port: 2242
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wrc_cloud?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: wrc8848
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Shanghai

mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml
#  typeAliasesPackage: com.wrc.cloud.entity