server:
  port: 9527

spring:
  application:
    name: CLOUD-GATEWAY
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    #############################新增网关配置###########################
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        #        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
        ##          uri: http://localhost:9001         #匹配后提供服务的路由地址
        #          uri: lb://nacos-payment-provider #匹配后提供服务的路由地址
        #          predicates:
        #            - Path=/payment/nacos/**         # 断言，路径相匹配的进行路由

        #        - id: payment_routh2
        ##          uri: http://localhost:8401
        #          uri: lb://cloudalibaba-sentinel-service
        #          predicates:
        #            - Path=/test**
        #            - After=2023-01-24T10:07:28.627+08:00[Asia/Shanghai]

        - id: sentiment-analysis-2242
          # uri: http://localhost:8001
          uri: lb://ANALYSIS-MANAGE #匹配后提供服务的路由地址,lb为负载均衡的其中一种模式
          predicates:
            - Path= /index.html, /static/**, /api/bili/**, /api/weibo/**, /api/twitter/**, /api/btc/**
        #            - Path= /**

        - id: Auth-2245
          uri: lb://CLOUD-AUTH
          predicates:
            - Path= /api/auth/**

  ####################################################################
  #  解决某些错误,启动覆盖
  main:
    allow-bean-definition-overriding: true





