version: '3.1'

services:
  mysql:
    image: mysql:8.0.17
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: wrc8848
      TZ: Asia/Shanghai
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    ports:
      - 3306:3306
    volumes:
      # 初始化
      # - ./mysql/init/:/docker-entrypoint-initdb.d/
      # 挂挂载配置文件
      - ./mysql/conf:/etc/mysql/conf.d
      # 挂载日志
      - ./mysql/logs:/var/log/mysql
      # 挂载数据
      - ./mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    networks:
      - cloud-sent

  redis:
    image: redis:6.0
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./redis/conf/redis.conf:/etc/redis/redis.conf
      - ./redis/data:/data
      - ./redis/logs:/logs
    environment:
      - TZ="Asia/Shanghai"
    networks:
      - cloud-sent

  rabbitmq:
    restart: always
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - /etc/localtime:/etc/localtime
    networks:
      - cloud-sent

  nacos:
    image: nacos/nacos-server:v2.2.0-slim
    container_name: nacos
    environment:
      - PREFER_HOST_MODE=ip
      - MODE=standalone
    volumes:
      - ./nacos/standalone-logs/:/home/nacos/logs
      # - ./nacos/config/custom.properties:/home/nacos/config/application.properties
    ports:
      - 8848:8848
      - 9555:9555
    restart: always
    networks:
      - cloud-sent

  nginx:
    container_name: nginx
    image: nginx:1.24.0
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d/:/etc/nginx/conf.d/ #/etc/nginx/conf.d/default.conf
      - ./nginx/cert:/home/cert # HTTPS证书目录挂载到容器的home目录下
      - /home/www/dist:/home/www/dist  # 挂载宿主机上的www目录到容器里的home目录下方便发布web项目
      - /home/www/picture:/home/www/picture
      - ./nginx/logs:/var/log/nginx # 把容器内的Nginx日志目录挂载到宿主机
      - /etc/localtime:/etc/localtime:ro #配置容器时间同步
    networks:
      - cloud-sent


networks:
  cloud-sent:
    name: cloud-sent
    driver: bridge
