version: '3.1'
# 数据保存到/data/cloud-sent
services:
  sentiment-analysis-manage:
    #启动服务时，先将build中指定的dockerfile打包成镜像，再运行该镜像
    image: cloud-sent-manage:0.9
    build:
      context: sentiment-analysis-manage #指定上下文目录dockerfile所在目录[相对、绝对路径都可以]
      dockerfile: Dockerfile #文件名称[在指定的context的目录下指定那个Dockerfile文件名称]
    container_name: sentiment-analysis-manage
    ports:
      - 2242:2242
    restart: always
    networks:
      - cloud-sent

  gateway9527:
    image: cloud-gateway:0.9
    build:
      context: gateway9527
      dockerfile: Dockerfile
    container_name: gateway9527
    ports:
      - 9527:9527
    restart: always
    networks:
      - cloud-sent

  cloud-auth:
    image: cloud-auth:0.9
    build:
      context: cloud-auth
      dockerfile: Dockerfile
    container_name: cloud-auth
    ports:
      - 2245:2245
    restart: always
    networks:
      - cloud-sent

networks:
  cloud-sent:
    name: cloud-sent
    external: true


